// Curated, broad list of Indian colleges & universities used to power the
// "Nearby college" autocomplete on the Add/Edit PG forms (an <input> + <datalist>).
// It is NOT exhaustive — India has 1000+ universities and ~40,000 colleges — so the
// field is a free-text input: owners can pick a suggestion OR type their own institution.
// Sorted alphabetically; keep entries unique.

export const COLLEGES = [
  "Aliah University, Kolkata",
  "Aligarh Muslim University (AMU)",
  "All India Institute of Medical Sciences (AIIMS), Delhi",
  "Amity University, Noida",
  "Amrita Vishwa Vidyapeetham, Coimbatore",
  "Anna University, Chennai",
  "Ashoka University, Sonipat",
  "Asansol Engineering College",
  "Assam University, Silchar",
  "Banaras Hindu University (BHU), Varanasi",
  "Bangalore University",
  "Bengal Engineering (IIEST Shibpur)",
  "Bennett University, Greater Noida",
  "Birla Institute of Technology (BIT) Mesra, Ranchi",
  "Birla Institute of Technology and Science (BITS) Pilani",
  "Calcutta Institute of Engineering and Management",
  "Chandigarh University",
  "Christ University, Bangalore",
  "Cochin University of Science and Technology (CUSAT)",
  "College of Engineering, Pune (COEP)",
  "Delhi Technological University (DTU)",
  "Dr. B. R. Ambedkar National Institute of Technology, Jalandhar",
  "Durgapur Institute of Advanced Technology and Management",
  "Gauhati University, Guwahati",
  "Guru Gobind Singh Indraprastha University (IP University), Delhi",
  "Hansraj College, Delhi",
  "Hindu College, Delhi",
  "Indian Institute of Management (IIM) Ahmedabad",
  "Indian Institute of Management (IIM) Bangalore",
  "Indian Institute of Management (IIM) Calcutta",
  "Indian Institute of Management (IIM) Indore",
  "Indian Institute of Management (IIM) Kozhikode",
  "Indian Institute of Management (IIM) Lucknow",
  "Indian Institute of Science (IISc), Bangalore",
  "Indian Institute of Technology (IIT) Bombay",
  "Indian Institute of Technology (IIT) Delhi",
  "Indian Institute of Technology (IIT) Dhanbad (ISM)",
  "Indian Institute of Technology (IIT) Gandhinagar",
  "Indian Institute of Technology (IIT) Guwahati",
  "Indian Institute of Technology (IIT) Hyderabad",
  "Indian Institute of Technology (IIT) Indore",
  "Indian Institute of Technology (IIT) Kanpur",
  "Indian Institute of Technology (IIT) Kharagpur",
  "Indian Institute of Technology (IIT) Madras",
  "Indian Institute of Technology (IIT) Patna",
  "Indian Institute of Technology (IIT) Roorkee",
  "Indian Institute of Technology (IIT) Ropar",
  "Indian Institute of Technology (IIT) Varanasi (BHU)",
  "Indian Institute of Information Technology (IIIT) Allahabad",
  "Indian Institute of Information Technology (IIIT) Bangalore",
  "Indian Institute of Information Technology (IIIT) Delhi",
  "Indian Institute of Information Technology (IIIT) Hyderabad",
  "Indian School of Mines (see IIT Dhanbad)",
  "Indian Statistical Institute (ISI), Kolkata",
  "Indraprastha Institute of Information Technology, Delhi",
  "Institute of Chemical Technology (ICT), Mumbai",
  "Jadavpur University, Kolkata",
  "Jamia Hamdard, Delhi",
  "Jamia Millia Islamia, Delhi",
  "Jawaharlal Nehru University (JNU), Delhi",
  "Jaypee Institute of Information Technology, Noida",
  "Jorhat Engineering College",
  "Kazi Nazrul University, Asansol",
  "KIIT University, Bhubaneswar",
  "Kirori Mal College, Delhi",
  "Lady Shri Ram College for Women, Delhi",
  "Lovely Professional University (LPU), Jalandhar",
  "Madras Christian College, Chennai",
  "Maharaja Sayajirao University of Baroda",
  "Maulana Abul Kalam Azad University of Technology (MAKAUT), West Bengal",
  "Malaviya National Institute of Technology (MNIT), Jaipur",
  "Manipal Institute of Technology (MIT), Manipal",
  "Miranda House, Delhi",
  "Motilal Nehru National Institute of Technology (MNNIT), Allahabad",
  "National Institute of Technology (NIT) Agartala",
  "National Institute of Technology (NIT) Calicut",
  "National Institute of Technology (NIT) Durgapur",
  "National Institute of Technology (NIT) Jamshedpur",
  "National Institute of Technology (NIT) Kurukshetra",
  "National Institute of Technology (NIT) Rourkela",
  "National Institute of Technology (NIT) Silchar",
  "National Institute of Technology (NIT) Surathkal (NITK)",
  "National Institute of Technology (NIT) Tiruchirappalli (NIT Trichy)",
  "National Institute of Technology (NIT) Warangal",
  "National Law School of India University (NLSIU), Bangalore",
  "Netaji Subhas University of Technology (NSUT), Delhi",
  "O. P. Jindal Global University, Sonipat",
  "Osmania University, Hyderabad",
  "Panjab University, Chandigarh",
  "Presidency University, Kolkata",
  "PSG College of Technology, Coimbatore",
  "Pondicherry University",
  "R. V. College of Engineering, Bangalore",
  "Rajiv Gandhi Institute of Petroleum Technology",
  "Ramaiah Institute of Technology, Bangalore",
  "SRM Institute of Science and Technology, Chennai",
  "Savitribai Phule Pune University",
  "Shiv Nadar University, Greater Noida",
  "Shri Ram College of Commerce (SRCC), Delhi",
  "Sikkim Manipal University",
  "St. Stephen's College, Delhi",
  "St. Xavier's College, Kolkata",
  "St. Xavier's College, Mumbai",
  "Symbiosis International University, Pune",
  "Tezpur University",
  "Thapar Institute of Engineering and Technology, Patiala",
  "University of Calcutta, Kolkata",
  "University of Delhi (DU)",
  "University of Hyderabad",
  "University of Kerala, Thiruvananthapuram",
  "University of Lucknow",
  "University of Mumbai",
  "University of Rajasthan, Jaipur",
  "Vellore Institute of Technology (VIT), Vellore",
  "Vidyasagar University, Midnapore",
  "Visva-Bharati University, Santiniketan",
  "Visvesvaraya National Institute of Technology (VNIT), Nagpur",
  "West Bengal State University, Barasat",
  "West Bengal University of Technology (see MAKAUT)",
];
